Carrousel
Gillian59/game-ecommerce pull request #38
Opened 2020-10-21 14:47 UTC by UnpolariZ

test de carrousel

2020-10-21 16:28 UTC, Remilde commented on public/styles/main.css
> +  /*background-color: rgb(73, 40, 82);*/
Autre choix de couleur possible

2020-10-22 09:51 UTC, UnpolariZ reviewed
je peux pas approuver :'(

2020-10-22 09:58 UTC, TheRealAstoo commented
> je peux pas approuver :'(

C'est normal, t'es pas dans les "reviewers" et faut faire un "approve" je pense.

2020-10-22 10:00 UTC, TheRealAstoo requested changes
Go delete the files : 

- public/images/breathofthewild.jpg
- public/images/jeux-video-2020.jpg
- public/images/platform.jpg

And i'll approve this :)

2020-10-22 10:08 UTC, TheRealAstoo approved these changes
Well played !

2020-10-22 10:08 UTC, merged